server:
  port: 8111

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account_from?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  application:
    name: sample-tcc-to

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: org.example.to.entity
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: auto

dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: org.example.to.dubbo
  registry:
    address: nacos://127.0.0.1:8848

seata:
  application-id: sample-tcc-to
  tx-service-group: sample-seata-group
  client:
    rm:
      report-success-enable: true
  service:
    vgroup-mapping:
      sample-seata-group: default
    grouplist:
      default: 127.0.0.1:8091
  transport:
    enable-client-batch-send-request: true
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
