server:
  port: 8103

spring:
  application:
    name: sample-business


dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: org.example.business.service
  registry:
    address: nacos://127.0.0.1:8848

seata:
  application-id: sample-business
  tx-service-group: sample-seata-group
  client:
    rm:
      report-success-enable: true
  service:
    vgroup-mapping:
      sample-seata-group: default
    grouplist:
      default: 127.0.0.1:8091
  transport:
    enable-client-batch-send-request: true
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
